import { 
  UsersIcon, 
  DocumentTextIcon,
  Squares2X2Icon,
  ClipboardDocumentListIcon,
  TicketIcon,
  ShoppingBagIcon,
  UserGroupIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  CalendarIcon,
  BriefcaseIcon,
  PhoneIcon,
  InboxIcon,
  ArchiveBoxIcon,
  ArrowDownTrayIcon,
} from "@heroicons/react/24/outline";

export const navigation = [
  { name: 'Dashboard', id: 'dashboard', href: '/', icon: Squares2X2Icon },
  { name: 'EA-MD Hub', id: 'ea-md-hub', href: '/ea-md-hub', icon: BriefcaseIcon },
  { name: 'Users', id: 'users', href: '/users', icon: UsersIcon },
  { name: 'Delegations', id: 'delegations', href: '/delegations', icon: DocumentTextIcon },
  { name: 'Checklists', id: 'checklists', href: '/checklists', icon: ClipboardDocumentListIcon },
  { name: 'Help Tickets', id: 'tickets', href: '/tickets', icon: TicketIcon },
  { name: 'O2D', id: 'o2d', href: '/o2d', icon: ShoppingBagIcon },
  { name: 'Metrix', id: 'metrix', href: '/metrix', icon: ChartBarIcon },
  { name: 'I2R', id: 'i2r', href: '/i2r', icon: ArchiveBoxIcon },
  { name: 'I2R Packing', id: 'i2r-packing', href: '/i2r-packing', icon: ArchiveBoxIcon },
  { name: 'Item Receive (PACKING)', id: 'item-receive-packing', href: '/item-receive-packing', icon: ArchiveBoxIcon },
  { name: 'Replace', id: 'replace', href: '/replace', icon: ArchiveBoxIcon },
  { name: 'GRN', id: 'grn', href: '/grn', icon: ArrowDownTrayIcon },
  { name: 'IMS', id: 'ims', href: '/ims', icon: InboxIcon },
  { name: 'Party Management', id: 'party-management', href: '/party-management', icon: UserGroupIcon },
  { name: 'Attendance', id: 'attendance', href: '/attendance', icon: ClipboardDocumentListIcon },
  { name: 'Score', id: 'score', href: '/score', icon: ChartBarIcon },
  { name: 'Chat', id: 'chat', href: '/chat', icon: ChatBubbleLeftRightIcon },
  { name: 'Scheduler', id: 'scheduler', href: '/scheduler', icon: CalendarIcon },
  { name: 'Scot', id: 'scot', href: '/scot', icon: PhoneIcon },
];
