"use client";

import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "./ThemeProvider";
import { ToastProvider } from "./ToastProvider";
import { LoaderProvider } from "./LoaderProvider";
import { Amplify } from "aws-amplify";
// @ts-ignore - This file is generated by Amplify after sandbox/deployment
import outputs from "../../amplify_outputs.json";

// Configure Amplify safely
if (outputs && Object.keys(outputs).length > 0) {
  try {
    Amplify.configure(outputs);
  } catch (e) {
    console.error("Amplify configuration failed:", e);
  }
} else {
  console.warn("Amplify Outputs missing or empty. Subscriptions and Auth may not work correctly on this build.");
}

export default function Providers({ children }: { children: React.ReactNode }) {
  return (
    <SessionProvider>
      <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
        <ToastProvider>
          <LoaderProvider>
            {children}
          </LoaderProvider>
        </ToastProvider>
      </ThemeProvider>
    </SessionProvider>
  );
}
